const AIGenerated =
  "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg?quality=75&auto=webp";

export const filesDefault = [
  {
    id: "0",
    folderId: "folder-one",
    filename: "ai-0",
    title: "AI Generated Image 0",
    uploadedDate: new Date(2022, 5, 24),
    src: AIGenerated,
    type: "jpeg",
  },
  {
    id: "1",
    folderId: "folder-one",
    filename: "ai-1",
    title: "AI Generated Image 1",
    uploadedDate: new Date(2022, 5, 11),
    src: AIGenerated,
    type: "png",
  },
  {
    id: "2",
    folderId: "folder-one",
    filename: "ai-2",
    title: "AI Generated Image 2",
    uploadedDate: new Date(2022, 1, 4),
    src: AIGenerated,
    type: "tif",
  },
  {
    id: "3",
    folderId: "folder-one",
    filename: "ai-3",
    title: "AI Generated Image 3",
    uploadedDate: new Date(2021, 11, 13),
    src: AIGenerated,
    type: "gif",
  },
  {
    id: "4",
    folderId: "folder-two",
    filename: "ai-4",
    title: "AI Generated Image 4",
    uploadedDate: new Date(2021, 10, 24),
    src: AIGenerated,
    type: "jpeg",
  },
  {
    id: "5",
    folderId: "folder-two",
    filename: "ai-5",
    title: "AI Generated Image 5",
    uploadedDate: new Date(2021, 9, 2),
    src: AIGenerated,
    type: "jpeg",
  },
  {
    id: "6",
    folderId: "folder-two",
    filename: "ai-6",
    title: "AI Generated Image 6",
    uploadedDate: new Date(2021, 8, 22),
    src: AIGenerated,
    type: "jpg",
  },
  {
    id: "7",
    folderId: "folder-two",
    filename: "ai-7",
    title: "AI Generated Image 7",
    uploadedDate: new Date(2020, 7, 19),
    src: AIGenerated,
    type: "jpg",
  },
];
